name: Node Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Clean install node dependncies
        run: npm ci
      - name: Linting code
        run: npm run lint
      - name: Running unit tests
        run: npm run test:unit
      - name: Building
        run: npm run build
